# Generated by Django 5.2.17 on 2026-09-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='key',
            field=models.CharField(choices=[('runner.recording', 'runner.recording — teach mode (recording a flow)'), ('runner.runs', 'runner.runs — running scripts and suites'), ('runner.onboarding', 'runner.onboarding — creating suites, pages and page scans'), ('runner.origins', 'runner.origins — allowing or removing origins'), ('runner.driving', 'runner.driving — opening URLs and driving the page from the console'), ('runner.heal', 'runner.heal — fixing broken steps automatically'), ('control.signup', 'control.signup — self-service sign-up (including sign-up through Google)'), ('control.invitations', 'control.invitations — issuing and accepting invitations'), ('control.google', 'control.google — Google sign-in'), ('control.passkeys', 'control.passkeys — passkey (WebAuthn) sign-in')], help_text='What each key guards — runner.recording: teach mode (recording a flow); runner.runs: running scripts and suites; runner.onboarding: creating suites, pages and page scans; runner.origins: allowing or removing origins; runner.driving: opening URLs and driving the page from the console; runner.heal: fixing broken steps automatically; control.signup: self-service sign-up (including sign-up through Google); control.invitations: issuing and accepting invitations; control.google: Google sign-in; control.passkeys: passkey (WebAuthn) sign-in. A key named in GC_SWITCHES_OFF is off whatever its row says: the environment wins.', max_length=40, unique=True),
        ),
    ]
